SELECT tp.NM_PRODUCT, SUM(QT_ITEM) AS QT_ITEM FROM TB_NF_ITEM tni 
INNER JOIN TB_PRODUCT tp ON TNI.CD_PRODUCT = tp.CD_PRODUCT
GROUP BY tni.CD_NF, tp.NM_PRODUCT
ORDER BY tp.NM_PRODUCT; 

SELECT TRUNC(TN.DT_EMISSION) AS DATA, SUM(tn.NR_ITEM) QT_ITEM FROM TB_NF TN
GROUP BY TRUNC(TN.DT_EMISSION)
ORDER BY TRUNC(TN.DT_EMISSION) ;

SELECT tni.CD_PRODUCT, sum(tni.QT_ITEM * tni.VL_PRODUCT) FROM TB_NF_ITEM tni
GROUP BY tni.CD_PRODUCT;

SELECT tni.CD_PRODUCT, MIN(tni.VL_PRODUCT) VL_PRODUCT_MIN FROM TB_NF_ITEM tni
GROUP BY tni.CD_PRODUCT;

SELECT TRUNC(TNI.DT_EMISSAO), MIN(tni.VL_PRODUCT) FROM TB_NF_ITEM tni;

SELECT TRUNC(TNI.DT_EMISSAO), tni.CD_PRODUCT, MIN(tni.VL_PRODUCT) VL_PRODUCT_MIN FROM TB_NF_ITEM tni
GROUP BY TRUNC(TNI.DT_EMISSAO), tni.CD_PRODUCT
ORDER BY TRUNC(TNI.DT_EMISSAO), TNI.CD_PRODUCT ;

SELECT TRUNC(TNI.DT_EMISSAO), tni.CD_PRODUCT, MAX(tni.VL_PRODUCT) VL_PRODUCT_MIN FROM TB_NF_ITEM tni
GROUP BY TRUNC(TNI.DT_EMISSAO), tni.CD_PRODUCT
ORDER BY TRUNC(TNI.DT_EMISSAO), TNI.CD_PRODUCT ;